blank_issues_enabled: false

# Optional: add contact links later once repository URL/communication channels are set.
# contact_links:
#   - name: Project Docs (Handoff)
#     url: https://github.com/<owner>/<repo>/blob/main/docs/HANDOFF.md
#     about: Start here for setup, status, and next steps.

